name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: File modification
        run: echo "Last update: $(date)" >> last-update.txt

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Autoupdate: $(date)"
